routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ContactController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('contacts.create');
});
// Route::post('/store',[ContactController::class,'store'])->name('contacts.store');
Route::resource('contacts', ContactController::class);

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    use HasFactory;

    protected $fillable = [
        'id','first_name','last_name','date','email','password','address','address2','country','state','status',
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Models\Contact;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use PhpParser\Node\Expr\Cast\Array_;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Contact $contact)
    {
        $formfields = $contact->all();

        return view('contacts.index', compact('formfields'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $formfields = $request->validate([
            'first_name' => 'required',
            'last_name' => 'required',
            'date' => 'required',
            'email' => ['required','email'],
            'password' => 'required',
            'address' => 'required',
            'address2' => 'required',
            'country' => ['required'],
            'state' => ['required'],
            'status' => ['required'],
        ]);
        $formfields = $request->except(['_token']);
        Contact::create($formfields)->with('message','Stored Successfully');
        // $data = Contact::create($formfields);
        return redirect()->route('contacts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $formfields = Contact::find($id);
        return view('contacts.show', compact('formfields'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $formfields = Contact::find($id);
        return view('contacts.edit',compact('formfields'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request , $id)
    {
       $formfields = $request->all();
       $contact = Contact::find($id);
       $contact->first_name = $formfields["first_name"];
       $contact->last_name = $formfields["last_name"];
       $contact->date = $formfields["date"];
       $contact->email = $formfields["email"];
       $contact->password = $formfields["password"];
       $contact->address = $formfields["address"];
       $contact->address2 = $formfields["address2"];
       $contact->country = $formfields["country"];
       $contact->state = $formfields["state"];
       $contact->save();

       return redirect()->route('contacts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $formfields = Contact::find($id);
       $formfields->delete();
       return redirect()->route('contacts.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/contacts/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ContactManager</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{{asset('style.css')}}">
</head>
<body>
    <div class="container m-4 p-4" style="border:2px solid black;">
        <div><h2>Registration Form</h2></div>
        <form action="{{route('contacts.store')}}" method="POST">
            @csrf
            <div class="form-row flex">
              <div class="form-group col-md-5">
                <label for="first_name">First Name</label>
                <input type="text" class="form-control" name="first_name" placeholder="first_name" >
              </div>
              <div class="form-group col-md-5 mx-1">
                <label for="last_name">Last Name</label>
                <input type="text" class="form-control" name="last_name" placeholder="last_name">
              </div>
              <div class="form-group col-md-2">
                <label for="date">Date of Birth</label>
                <input type="date" class="form-control" name="date">
              </div>
            </div>
            <div class="form-row flex">
                <div class="form-group col-md-6 mx-1">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" name="email" placeholder="email">
                </div>
                <div class="form-group col-md-6">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" name="password" placeholder="password">
                </div>
            </div>
            <div class="form-group ">
              <label for="address">Address</label>
              <input type="text" class="form-control" name="address" placeholder="Enter your address">
            </div>
            <div class="form-group ">
              <label for="address2">Address 2</label>
              <input type="text" class="form-control" name="address2" placeholder="Enter your second address ">
            </div>
            <div class="form-row flex">
              <div class="form-group col-md-5">
                <label for="country">Country</label>
                <select name="country" class="form-control">
                    <option selected></option>
                    <option>India</option>
                  </select>
              </div>
              <div class="form-group col-md-4 mx-1">
                <label for="state">State</label>
                <select name="state" class="form-control">
                  <option selected></option>
                  <option>Maharashtra</option>
                </select>
              </div>
              <div class="form-group col-md-3 ">
                <label for="status">Status</label>
                <select name="status" class="form-control">
                    <option selected></option>
                    <option>InActive</option>
                    <option>Active</option>
                  </select>
              </div>
            </div>
            <button type="submit" class="btn btn-primary my-2">Create Contact</button>
          </form>
    </div>

    <script src="{{ asset('app.js') }}"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

resources/views/contacts/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ContactManager</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{{asset('style.css')}}">
</head>
<body>
    <div class="container m-4 p-4" style="border:2px solid black;">
        <div><h2>Update Contacts</h2></div>
        <form action="{{route('contacts.update',$formfields->id)}}" method="POSt">
            @csrf
            @method('PUT')
            <div class="form-row flex">
              <div class="form-group col-md-5">
                <label for="first_name">First Name</label>
                <input type="text" value="{{$formfields->first_name}}" class="form-control" name="first_name" placeholder="first_name" >
              </div>
              <div class="form-group col-md-5 mx-1">
                <label for="last_name">Last Name</label>
                <input type="text" value="{{$formfields->last_name}}" class="form-control" name="last_name" placeholder="last_name">
              </div>
              <div class="form-group col-md-2">
                <label for="date">Date of Birth</label>
                <input type="date" value="{{$formfields->date}}" class="form-control" name="date">
              </div>
            </div>
            <div class="form-row flex">
                <div class="form-group col-md-6 mx-1">
                    <label for="email">Email</label>
                    <input type="email" value="{{$formfields->email}}" class="form-control" name="email" placeholder="email">
                </div>
                <div class="form-group col-md-6">
                    <label for="password">Password</label>
                    <input type="password" value="{{$formfields->password}}" class="form-control" name="password" placeholder="password">
                </div>
            </div>
            <div class="form-group ">
              <label for="address">Address</label>
              <input type="text" value="{{$formfields->address}}"  class="form-control" name="address" placeholder="Enter your address">
            </div>
            <div class="form-group ">
              <label for="address2">Address 2</label>
              <input type="text" value="{{$formfields->address2}} "class="form-control" name="address2" placeholder="Enter your second address ">
            </div>
            <div class="form-row flex">
              <div class="form-group col-md-5">
                <label for="country">Country</label>
                <select name="country" class="form-control">
                    <option selected>{{$formfields->country}}</option>
                    <option>India</option>
                  </select>
              </div>
              <div class="form-group col-md-4 mx-1">
                <label for="state">State</label>
                <select name="state" class="form-control">
                  <option selected>{{$formfields->state}}</option>
                  <option>Maharashtra</option>
                </select>
              </div>
              <div class="form-group col-md-3 ">
                <label for="status">Status</label>
                <select name="status" class="form-control">
                    <option selected>{{$formfields->status}}</option>
                    <option>InActive</option>
                    <option>Active</option>

                  </select>
              </div>
            </div>
            <button type="submit" class="btn btn-primary my-2">Update</button>
          </form>
    </div>

    <script src="{{ asset('app.js') }}"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

resources/views/contacts/flash-message.blade.php
{{-- @php
if(session()->has('message'))
{
    <li class="list-group-item list-group-item-primary" style="position:absolute;top:0px, bottom:0px">{{$message}}</li>
}
@endphp --}}

resources/views/contacts/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Contact Details</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{{asset('style.css')}}">
</head>
<body>
    <div class="container">
        <div class="list-group" >
            <div class="column-header" style="display:flex; justify-content:space-evenly;">
                <span class="headings">First Name</span>
                <span class="headings">Last Name</span>
                <span class="headings">Date of Birth</span>
            </div>
        @foreach($formfields as $field)
        <li class="contact-row flex">
            <a href="#" class="list-group-item list-group-item-action"> {{$field->first_name}}</a>
            <a href="#" class="list-group-item list-group-item-action">{{$field->last_name}}</a>
            <a href="#" class="list-group-item list-group-item-action">{{$field->date}}</a>

            <form action="{{route('contacts.destroy',$field->id)}}" method="POST">
            @csrf
            @method('DELETE')
            <button type="submit" class="btn btn-danger">Delete</button>
            </form>
            <a href="{{route('contacts.show',$field->id)}}" type="button" class="btn btn-success" style="height : 38px;">Show<a>
        </li>
        @endforeach
        </div>
    </div>

    <script src="{{ asset('app.js') }}"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

resources/views/contacts/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Contact Details</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{{asset('style.css')}}">
</head>
<body>
    <div class="container m-5" style="display:flex;flex-direction:column;height:600px;justify-content:center;">
        <h3>Contact Details</h3>
        <div class="list-group" >
            <ul class=" list-group" style="flex-direction:column;">
                <li class="list-group-item">First Name : <strong>{{$formfields->first_name}}</strong></li>
                <li class="list-group-item">Last Name  : <strong>{{$formfields->last_name}}</strong></li>
                <li class="list-group-item">Email  : <strong>{{$formfields->email}}</strong></li>
                <li class="list-group-item">Password  : <strong>{{$formfields->password}}</strong></li>
                <li class="list-group-item">Address  : <strong>{{$formfields->address}}</strong></li>
                <li class="list-group-item">Address2 : <strong>{{$formfields->address2}}</strong></li>
                <li class="list-group-item">Created_on : <strong>{{$formfields->created_at}}</strong></li>
                <li class="list-group-item">Updated_on : <strong>{{$formfields->updated_at}}</strong></li>
                <a href="{{route('contacts.edit',$formfields->id)}}" class="btn btn-primary" role="button">Edit</a>
                <a href="{{route('contacts.index')}}" class="btn btn-secondary" role="button">BACK</a>


            </ul>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>